Repository DeveloperAcademy-POSTECH/MC3_Team10_TalTal, pull requests merged in 2022-08, with the labels that each got.

#27 [2022.08.01] 오류 수정 함수명이 SaveFlection으로 되어있는걸 -> fetchReflection으로 변경해야 동작합니다.
  TalTal/TalTal/Models/MissionDataManager.swift
Labels: bug

#28 [2022.07.31] 미션 클리어 후에 코어 데이터 저장
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/Controllers/MissionClearViewController.swift
  TalTal/TalTal/Models/MissionDAO.swift
  TalTal/TalTal/Models/MissionDataManager.swift
Labels: bug

#29 [2022.08.01]같이 작업해야할 부분 주석 추가
  TalTal/TalTal.xcodeproj/project.pbxproj
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
Labels: enhancement

#31 [2022.08.01] MissionViewController의 유저디폴트 수정 및 뷰 수정
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
Labels: enhancement

#33 [2022.08.01] MissionViewController와 코어 데이터 버그 수정 및 앱 아이콘 추가
  TalTal/TalTal/Assets.xcassets/.DS_Store
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/100.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/1024.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/114.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/120.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/128.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/144.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/152.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/16.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/167.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/172.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/180.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/196.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/20.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/216.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/256.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/29.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/32.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/40.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/48.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/50.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/512.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/55.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/57.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/58.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/60.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/64.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/72.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/76.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/80.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/87.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/88.png
  TalTal/TalTal/Assets.xcassets/AppIcon.appiconset/Contents.json
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/appstore.png
Labels: bug, enhancement

#34 [2022.08.01]일간미션 클리어
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
Labels: bug

#35 [2022.08.01] 주간 퀘스트 리프레쉬 문제
  TalTal/TalTal/Models/MissionDataManager.swift
Labels: bug

#36 [2022.08.01] 주간 퀘스트 리프레쉬 문제(재수정)
  TalTal/TalTal/Models/MissionDataManager.swift
Labels: bug

#37 [2022.08.01] MissionViewController의 변수명 오타 수정 및 configureMission 에러 수정
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/Controllers/ReflectionViewController.swift
Labels: bug

#38 [2022.08.02] 디테일 수정
  TalTal/TalTal/ AppDelegate.swift
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/Models/MissionDataManager.swift
  TalTal/TalTal/StoryBoard/Reflection.storyboard
  TalTal/TalTal/Views/HistoryCell.swift
Labels: bug, enhancement

#39 [2022.08.02] 로컬라이징 기초 작업 및 런치스크린추가
  TalTal/TalTal.xcodeproj/project.pbxproj
  TalTal/TalTal/Assets.xcassets/launchScreenimage.imageset/Contents.json
  TalTal/TalTal/Assets.xcassets/launchScreenimage.imageset/launchScreenimage.jpeg
  TalTal/TalTal/Base.lproj/LaunchScreen.storyboard
  TalTal/TalTal/Controllers/Mission/MissionQuestView.swift
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/Extension/StirngExtension.swift
  TalTal/TalTal/en.lproj/Localizable.strings
  TalTal/en.lproj/Localizable.strings
  TalTal/ko.lproj/Localizable.strings
Labels: enhancement

#40 [2022.08.02] 개인정보 처리 파일 추가
  개인정보처리.md
Labels: enhancement

#41 [2022.08.02] 앱 버전 정보 수정
  TalTal/TalTal.xcodeproj/project.pbxproj
Labels: enhancement

#43 [2022.08.03] 히스토리뷰 완료 미션이 없을 때, 알림문구 뷰잉 및 런치스크린 이미지 크기 수정
  TalTal/TalTal/Base.lproj/LaunchScreen.storyboard
  TalTal/TalTal/Controllers/HistoryViewController.swift
  TalTal/TalTal/StoryBoard/History.storyboard
Labels: bug

#44 [2022.08.03] 심사 제출을 위해 빌드버전을 1.0.0(1) -> 1.0.1(2)로 수정하였습니다.
  TalTal/TalTal.xcodeproj/project.pbxproj
Labels: bug, enhancement

#45 [2022.08.04] HOTFIX브랜치 Develop에 병합
  TalTal/TalTal.xcodeproj/project.pbxproj
  TalTal/TalTal/Base.lproj/LaunchScreen.storyboard
  TalTal/TalTal/Controllers/HistoryViewController.swift
  TalTal/TalTal/StoryBoard/History.storyboard
Labels: enhancement

#46 [2022.08.04] 미션추가, ipod터치 대응, 한국어 앱이름 추가
  TalTal/TalTal.xcodeproj/project.pbxproj
  TalTal/TalTal/Controllers/ReflectionViewController.swift
  TalTal/TalTal/Models/MissionDataManager.swift
  TalTal/en.lproj/InfoPlist.strings
  TalTal/en.lproj/Localizable.strings
  TalTal/ko.lproj/InfoPlist.strings
  TalTal/ko.lproj/Localizable.strings
Labels: enhancement

#48 [2022.08.12] EndingVeiw추가를 위한 기초작업
  TalTal/TalTal.xcodeproj/project.pbxproj
  TalTal/TalTal/Controllers/EndingViewController.swift
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/StoryBoard/Ending.storyboard
  TalTal/TalTal/StoryBoard/Mission/Mission.storyboard
Labels: enhancement

#49 [Fix] TabBarItem 로컬라이징
  TalTal/TalTal/Controllers/HistoryViewController.swift
  TalTal/TalTal/Controllers/Mission/MissionViewController.swift
  TalTal/TalTal/Controllers/TabbarViewController.swift
  TalTal/TalTal/StoryBoard/History.storyboard
  TalTal/TalTal/StoryBoard/Mission/Mission.storyboard
  TalTal/en.lproj/Localizable.strings
  TalTal/ko.lproj/Localizable.strings
Labels: enhancement

#50 [Docs] Readme 작업
  .DS_Store
  img/.DS_Store
  img/Presentation/.DS_Store
  img/Presentation/MC3_오후_10팀_TalTal.001.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.002.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.003.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.004.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.005.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.006.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.007.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.008.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.009.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.010.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.011.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.012.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.013.gif
  img/Presentation/MC3_오후_10팀_TalTal.014.gif
  img/Presentation/MC3_오후_10팀_TalTal.015.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.016.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.017.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.018.jpeg
  img/Presentation/MC3_오후_10팀_TalTal.019.jpeg
  img/appLogo.jpg
  img/appstore_qrcode.png
  img/main_long.jpg
  readme.md
Labels: documentation

#52 [2022.08.23] 엔딩뷰 구현
  TalTal/TalTal/Controllers/EndingViewController.swift
  TalTal/TalTal/StoryBoard/Ending.storyboard
Labels: enhancement
